/// Flutter icons MyFlutterApp
/// Copyright (C) 2020 by original authors @ fluttericon.com, fontello.com
/// This font was generated by FlutterIcon.com, which is derived from Fontello.
///
/// To use this font, place it in your fonts/ directory and include the
/// following in your pubspec.yaml
///
/// flutter:

///
///
///
import 'package:flutter/widgets.dart';

class MyFlutterAppH {
  MyFlutterAppH._();

  static const _kFontFam = 'hamid';
  static const _kFontPkg = null;

  static const IconData addidas =
      IconData(0xe800, fontFamily: _kFontFam, fontPackage: _kFontPkg);

}

